# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fbb306e4aadae4141f7b45500f16f6095315ee0f9ac45791a81d29617c4c6573b0881965ed6ba0e6b8c57a05ef1337425f0d820658b53dc062cbade4b03f361

test:
  secret_key_base: 60a25c181217b1db197f3cb6cbabc3961ed1b6ed62a1c3f92cc8fda90f337b8494fb73809629eacd3ddc0fee0cc640dbaddcfece0e78fbfdceeacdfb963944b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
